-- Storage policies for the private 'proformas' bucket.
-- Create the bucket first (Storage → New bucket → name 'proformas' → Private),
-- then run this so signed-in users can upload/read proforma PDFs.
--
-- (Signed links generated by the app work for the customer with no login;
--  these policies only govern who can PUT files in and manage them.)

do $$ begin
  create policy "proformas auth read" on storage.objects
    for select to authenticated using (bucket_id = 'proformas');
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "proformas auth insert" on storage.objects
    for insert to authenticated with check (bucket_id = 'proformas');
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "proformas auth update" on storage.objects
    for update to authenticated using (bucket_id = 'proformas') with check (bucket_id = 'proformas');
exception when duplicate_object then null; end $$;

do $$ begin
  create policy "proformas auth delete" on storage.objects
    for delete to authenticated using (bucket_id = 'proformas');
exception when duplicate_object then null; end $$;
